from datetime import datetime, timedelta, timezone
import httplib2
from googleapiclient.discovery import build
from oauth2client.service_account import ServiceAccountCredentials
from writeToGoogleDoc import write_to_google_doc

def test_write_to_google_doc():
    doc_name = "Test Report"
    doc_text = "This is a test report generated by the write_to_google_doc function."
    
    # Execute the function
    write_to_google_doc(doc_text, doc_name)
    
    # Verify the file was updated recently
    SERVICE_ACCOUNT_FILE = 'service_account.json'
    SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly']

    # Authenticate
    creds = ServiceAccountCredentials.from_json_keyfile_name(SERVICE_ACCOUNT_FILE, SCOPES)
    http_auth = creds.authorize(httplib2.Http())
    drive_service = build('drive', 'v3', http=http_auth)

    # Find the document
    query = f"name='{doc_name}' and mimeType='application/vnd.google-apps.document'"
    response = drive_service.files().list(q=query, spaces='drive', fields='files(id, name, modifiedTime)').execute()
    files = response.get('files', [])

    assert files, f"Document '{doc_name}' not found."

    # Check modified time
    # Google Drive returns RFC 3339 format like '2023-10-01T12:00:00.000Z'
    modified_time_str = files[0].get('modifiedTime').replace('Z', '+00:00')
    modified_time = datetime.fromisoformat(modified_time_str)
    current_time = datetime.now(timezone.utc)

    # Assert update was within the last 1 minute
    time_diff = current_time - modified_time
    assert time_diff < timedelta(minutes=1), f"File was not updated recently. Last modified: {modified_time}, Now: {current_time}"
    print(f"Test Passed: '{doc_name}' was updated {time_diff.total_seconds():.2f} seconds ago.")